development:
  clients:
    default:
      database: rails_api_development
      hosts:
        - localhost:27017
      options:
        user: 'root'
        password: 'example'
        roles:
          - 'dbOwner'
        auth_mech: :scram
        auth_source: admin

test:
  clients:
    default:
      database: rails_api_test
      hosts:
        - localhost:27017
      options:
        user: 'root'
        password: 'example'
        roles:
          - 'dbOwner'
        auth_mech: :scram
        auth_source: admin
        read:
          mode: :primary
        max_pool_size: 1
